# Generated by Django 4.1.7 on 2023-04-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0004_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
