# Generated by Django 4.1.7 on 2023-04-07 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0006_register_form'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_form',
        ),
    ]
