# Generated by Django 4.1.7 on 2023-07-11 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0022_remove_result_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register_form',
        ),
    ]
