# Generated by Django 4.1.7 on 2023-07-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skin', '0023_delete_register_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password1', models.CharField(max_length=200)),
                ('password2', models.CharField(max_length=200)),
            ],
        ),
    ]
