"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-&89#9wmtjt1z##zy^0p%_f0mw^q9z(0s4^*5ixk!)z_e43n^db'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'skin.apps.SkinConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    'django_auto_logout.middleware.auto_logout', # l'étape 1 pour installer django auto logout (après le pip install django-auto-logout et le pip install pytz), un module qui permet de déconnecter automatiquement l'utilisateur au bout d'un laps de temps de notre choix
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_auto_logout.context_processors.auto_logout_client', # étape 2 pour installer django auto logout
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
] 
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# SMTP configuration

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST ='smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'frederic.ferreira66@gmail.com' 
EMAIL_HOST_PASSWORD = 'ygmaqkwajhzjeoth' 
DEFAULT_FROM_EMAIL = 'frederic.ferreira66@gmail.com'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'ssl0.ovh.net'
# EMAIL_PORT = 465
# EMAIL_USE_SSL = True
# EMAIL_HOST_USER = 'test@osteopatheportovecchio.fr'
# DEFAULT_FROM_EMAIL = 'test@osteopatheportovecchio.fr'
# EMAIL_HOST_PASSWORD = 'wPUCzqGwfHPhQTN63R'


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Django session timeout
# étape 4 pour installer django auto logout
AUTO_LOGOUT = {'IDLE_TIME': 600, 'REDIRECT_TO_LOGIN_IMMEDIATELY': True,
               'MESSAGE': 'Votre session a expiré. Veuillez vous reconnecter.',
               } 


# implémentation de stripe pour les paiements en ligne

STRIPE_PUBLIC_KEY = 'pk_test_51NHOBbKFSQgUiiU0aSEm07wPbp64jgoLJIg10PX3mJGeIwPuLHrNP7I02Z7VIKugBKj0GPGwUePYovr8PxSpME8Q00k1j8E24m' # ajouter la clé publique (se connecter à son compte stripe pour la récupérer)
STRIPE_SECRET_KEY = 'sk_test_51NHOBbKFSQgUiiU0AxVGxdWm3EOo3skjrlY7FrGHoZ8zH5aSAqv5xuMFOoklxLbuEUeroryHUKSx0oJHwAUyGZvL00whu7hpO3' # ajouter la clé secrète (en l'occurrence la clé test)


# Openai secret key
OPEN_AI_SECRET_KEY = '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'
